-- Migration to add FAQ entries for DriveX
-- Tenant ID: 22c42919-4f33-4463-ae13-39cc26993c64

INSERT INTO faq_entries (tenant_id, category, question, answer, sort_order)
VALUES
('22c42919-4f33-4463-ae13-39cc26993c64', 'Security Deposit', 'How much is the security deposit and what does it cover?', 'The deposit starts at 1,000 AED and can go up to 3,000 AED depending on the luxe car you choose. It covers potential things like traffic fines, Salik tolls, or late returns. Since we offer unlimited mileage, you don''t even have to worry about extra distance charges!', 10),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Security Deposit', 'How can I pay the security deposit?', 'We keep it easy for you. You can block it on your credit card, or pay cash—we accept both AED in Dubai and IRR in Iran. International bank transfers are also fine, as long as you cover those pesky transfer fees.', 20),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Security Deposit', 'When and how will I get my deposit back?', 'You’ll get it back in 14 to 30 days. Why the wait? We just need to make sure all RTA and Dubai Police fines are accounted for. We can refund it in AED or IRR, whichever is more convenient for you.', 30),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Rules & Penalties', 'What happens if I smoke in the car?', 'We take pride in our spotless, new-car smell, so smoking is a no-go. It carries a fine of 1,000 AED from the police plus 500 AED from us. Let''s keep the interior fresh for your whole journey!', 40),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Rules & Penalties', 'What is your fuel policy?', 'Your car arrives with a full tank of gas, and we just ask for it back the same way. It saves you time and lets the next guest hit the road immediately!', 50),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Rules & Penalties', 'Are there any other charges I should know about?', 'Just the basics: Salik (tolls) are 6 AED per passage, and traffic violations have a 50 AED admin fee. But remember, we have zero mileage limits, so drive till your heart''s content! Car washes are on you—we appreciate you keeping the interior as clean as we delivered it.', 60),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Booking & Documents', 'What documents do I need to rent a car?', 'Super simple: just a clear photo of your international driver''s license, passport, visa, and your flight ticket. We''ll handle the rest so you can start your Dubai adventure.', 70),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Booking & Documents', 'How can I check for traffic fines?', 'You can hop onto the Dubai Police website anytime and check by plate number. It’s transparent and quick. We also apply a small 50 AED fee for handling any violations on our side.', 80),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Insurance', 'What''s the difference between Standard and Full Insurance?', 'Standard is free and covers the essentials. But if you want total peace of mind, go for Full Insurance—it covers body, glass, and tires, and removes the 3,000 AED excess liability. It’s the best way to enjoy our high-end fleet without a single worry!', 90),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Delivery & Convenience', 'Can you deliver the car to my location?', 'Definitely! One of our perks is free delivery and pickup anywhere in Dubai during our working hours (9 AM to 6 PM). We bring the car to you, and we take it back when you''re done—completely free of charge.', 100),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Driving Limits', 'Is there a limit on how many kilometers I can drive?', 'Nope! We believe your journey shouldn''t have limits. That’s why we offer unlimited mileage on all our vehicles. Drive as much as you want, wherever you want in the UAE!', 110),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Quality & Reliability', 'What kind of condition are the cars in?', 'You’re in for a treat. We have one of the newest and most diverse fleets in Dubai. Every vehicle is 100% healthy, meticulously inspected, and feels like it just rolled off the showroom floor. No old cars, no issues—just pure luxury and reliability.', 120),
('22c42919-4f33-4463-ae13-39cc26993c64', 'Location & Contact', 'Where is your office located and how can I reach you?', 'We’re right in the heart of the action! You can find us on Google Maps here: https://maps.app.goo.gl/JLbyg2qNbwZPmbWU7. If you need anything, give us a shout at +971 2 458 9322 or drop an email to info@drivex.ae. We''re always here to help!', 130),
('22c42919-4f33-4463-ae13-39cc26993c64', 'About DriveX', 'Who is DriveX and why should I choose you?', 'We’re more than just a rental company; we’re your luxury travel partner. Founded by Kamyar Neshastehchi with 10+ years of international expertise, we offer 300+ of the latest cars with unlimited mileage, free delivery, and 24/7 support. We treat every customer like family!', 140);
